services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/cykor_db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend/vite-project
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/vite-project:/app

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
